### PR TITLE
Nsamanta histoogy 1

### PR DESCRIPTION
**Pull request by nsamanta**
New PR for recent changes such as- renaming histology tifs and addtion of perifusion pdfs.

### CODE REVIEW

**Comment by dongbohu** [comment]
Are you sure this filename is correct?
```
HPAP-123_tail_20x.tif
```

**Comment by nsamanta** [comment]
> Are you sure this filename is correct?
> 
> ```
> HPAP-123_tail_20x.tif
> ```

@dongbohu it's not but one of the three commits above is about renaming this file. If you squash and merge will that commit stay?

**Comment by nsamanta** [comment]
> Are you sure this filename is correct?
> 
> ```
> HPAP-123_tail_20x.tif
> ```

@dongbohu I misunderstood your question. Yes I will rename it

**Comment by dongbohu** [comment]
If this command:
```
ls HPAP-*.tif
```
has any output, your file renaming is not complete yet.

**Comment by dongbohu** [comment]
Please be more careful from now on, because I may not be that lucky to notice the wrong filename immediately.

**Comment by nsamanta** [comment]
@dongbohu Can we delete this PR? I think the issue is because I mistakenly deleted my local branch, I am all over the place with this. 

Yesterday I renamed all these files and double-checked too, the second commit ([29ed97b](https://github.com/faryabiLab/hpap-public/pull/12/commits/29ed97befe4635930ce2c33ee78d6d160f53d671)) is where I performed the rename and as you can see the files were renamed-

123-his

But right now on `hpap-public/assets/histology` these changes are not reflected, because I deleted the branch. 

I apologize, I have made a flow-chart for myself and will strictly follow that moving forward. I thought after creating the PR, deleting the branch is okay, clearly not.

**Comment by nsamanta** [comment]
I will re-make the changes and create a new PR and test on dev etc and then ask you to merge

**Comment by dongbohu** [comment]
We can't delete a PR, so I am closing it now.

**Pull request closed without merging**
