### PR TITLE
Last updated HTML file from Vanderbilt

### PR DESCRIPTION
**Pull request by nsamanta**
Contains HTML file for Islet embedding by Immunofluorescence. 
Corrected:
1. Wrong `<br />` syntax and other syntaxes, plus text. 
2. Replaced symbols with HTML codes. 
3. CRLF --> LF
4. font size
5. unnecessary blank spaces

### CODE REVIEW

**Comment by nsamanta** [comment]
@yimsheng good catch! I am trying to match it to the style here: https://hpap.pmacs.upenn.edu/explore/workflow/islet-physiology-studies?protocol=6

When I tested before pushing, one line seemed to be above the pictures/tan;es and the other below them, right above reference, like so:

html-vandy-error

But I see here now that the pictures and the `reference ` title are not aligned (per the code i.e. middle or center)

**Comment by yimsheng** [comment]
@nsamanta yeah, this is because the column's `float:left` attribute make the two image kind of 'floating' in the page. To have the float attribute only have effects in the specified container(row in this case), you can add 
``` css
.row::after {
      content: "";
      clear: both;
      display: table;
    }
```
in the style tag
Another way of approaching it could be not using float instead use a container(row in this case) and set
```css
 .row {
      display: flex;
      justify-content: space-between;
    }
```
this should also work.

**Comment by yimsheng** [comment]
@nsamanta you can remove `float: left;' in .column. You can use the rest attributes to set the distance between the two images and the padding around them.

**Comment by nsamanta** [comment]
@yimsheng Just made another commit with the correction. Looks like your suggestion resolved the floating issue. Thanks!

**Pull request merged**
