### PR TITLE
updating the index.html file

### PR DESCRIPTION
**Pull request by nsamanta**
Testing index.html file for the News page with updated links to archived files

### CODE REVIEW

**Comment by nsamanta** [comment]
@yimsheng Let me know if you would like me to send you the actual html file if its easier to review. ALso please let me know if the file has issues with any of the following:
1. typos
2. indentation
3. More than 80 chars per line. There are a handful violating tis rule but I wanted to keep the code/text together
4. white space at the end of each line 

I checked the new links for the archived files and they were working.

**Comment by dongbohu** [comment]
@nsamanta As I told you before, when you work on HTML files, please try your best to follow the coding styles here:
https://google.github.io/styleguide/htmlcssguide.html

**Comment by yimsheng** [comment]
@nsamanta I have formatted the html and fixed those typos as I mentioned in review. FYI you can use code editor like vscode where you can format the code within one click.

**Comment by nsamanta** [comment]
> @nsamanta I have formatted the html and fixed those typos as I mentioned in the review. FYI you can use code editor like vscode where you can format the code within one click.

@yimsheng Thank you! I used sublime this time! I will go over the commits

**Pull request merged**
