### PR TITLE
Adding new metadata and updating old ones

### PR DESCRIPTION
**Pull request by nsamanta**
Updated the `Latest` sub-folder under `assets/metadata` to list most up-to-date metadata files for all assays and make them available for download from PANC-DB

### CODE REVIEW

**Comment by nsamanta** [comment]
Hi @yimsheng I did a `git pull` on `master` on `hpap` and `hpap-test` to pull these changes to `assets/metadata/latest`. But it worked on `hpap` and NOT on `hpap`. Basically I should be seeing some metadata spreadsheets with the date `2023-12-22` on both `hpap` and hpap-test`, but I ONLY see it on `test`. 

Here is a screenshot of the `git pull` on `hpap`:
```shell
s_hpap@hpap metadata$ git pull
From github.com-public:faryabilab/hpap-public
 - [deleted]         (none)     -> origin/nsamanta/update-latest-metadata
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 16 (delta 5), reused 15 (delta 5), pack-reused 0
Unpacking objects: 100% (16/16), 390.62 KiB | 950.00 KiB/s, done.
   3bb76a8..e9f7a5e  master     -> origin/master
Updating 3bb76a8..e9f7a5e
Fast-forward
 assets/metadata/latest/PancDB_CITE-seq_metadata_2023-12-22.xlsx                                                         | Bin 0 -> 22565 bytes
 assets/metadata/latest/PancDB_CODEX_metadata_2023-12-22.xlsx                                                            | Bin 0 -> 25440 bytes
 assets/metadata/latest/PancDB_CyTOF_metadata_2022-06-15.xlsx                                                            | Bin 26644 -> 0 bytes
 assets/metadata/latest/PancDB_CyTOF_metadata_2022-11-27.xlsx                                                            | Bin 0 -> 31450 bytes
 assets/metadata/latest/PancDB_Donors.xlsx                                                                               | Bin 118743 -> 28509 bytes
 assets/metadata/latest/PancDB_Imaging-mass-cytometry_metadata_2022-06-15.xlsx                                           | Bin 19452 -> 0 bytes
 assets/metadata/latest/PancDB_Imaging-mass-cytometry_metadata_2023-12-22.xlsx                                           | Bin 0 -> 28858 bytes
 assets/metadata/latest/PancDB_Patch-seq_patching_metadata_2023-05-24.xlsx                                               | Bin 19037 -> 0 bytes
 assets/metadata/latest/PancDB_Patch-seq_patching_metadata_2023-12-22.xlsx                                               | Bin 0 -> 19515 bytes
 assets/metadata/latest/PancDB_Patch-seq_sequencing_metadata_2022-06-15.xlsx                                             | Bin 37373 -> 0 bytes
 assets/metadata/latest/PancDB_Patch-seq_sequencing_metadata_2023-12-22.xlsx                                             | Bin 0 -> 209053 bytes
 assets/metadata/latest/PancDB_RNA-seq_metadata_2023-05-24.xlsx                                                          | Bin 18620 -> 0 bytes
 assets/metadata/latest/PancDB_RNA-seq_metadata_2023-12-13.xlsx                                                          | Bin 0 -> 23211 bytes
 assets/metadata/latest/{PancDB_Perifusion_metadata_2023-05-24.xlsx => PancDB_UPenn_Perifusion_metadata_2023-05-24.xlsx} | Bin
 assets/metadata/latest/PancDB_Vanderbilt_Perifusion_metadata_2023-12-22.xlsx                                            | Bin 0 -> 31014 bytes
 assets/metadata/latest/PancDB_scRNA-seq_metadata_2022-06-15.xlsx                                                        | Bin 67391 -> 0 bytes
 assets/metadata/latest/PancDB_scRNA-seq_metadata_2023-12-22.xlsx                                                        | Bin 0 -> 81924 bytes
 assets/metadata/latest/README.xlsx                                                                                      | Bin 217773 -> 220333 bytes
 18 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 assets/metadata/latest/PancDB_CITE-seq_metadata_2023-12-22.xlsx
 create mode 100644 assets/metadata/latest/PancDB_CODEX_metadata_2023-12-22.xlsx
 delete mode 100644 assets/metadata/latest/PancDB_CyTOF_metadata_2022-06-15.xlsx
 create mode 100644 assets/metadata/latest/PancDB_CyTOF_metadata_2022-11-27.xlsx
 delete mode 100644 assets/metadata/latest/PancDB_Imaging-mass-cytometry_metadata_2022-06-15.xlsx
 create mode 100644 assets/metadata/latest/PancDB_Imaging-mass-cytometry_metadata_2023-12-22.xlsx
 delete mode 100644 assets/metadata/latest/PancDB_Patch-seq_patching_metadata_2023-05-24.xlsx
 create mode 100644 assets/metadata/latest/PancDB_Patch-seq_patching_metadata_2023-12-22.xlsx
 delete mode 100644 assets/metadata/latest/PancDB_Patch-seq_sequencing_metadata_2022-06-15.xlsx
 create mode 100644 assets/metadata/latest/PancDB_Patch-seq_sequencing_metadata_2023-12-22.xlsx
 delete mode 100644 assets/metadata/latest/PancDB_RNA-seq_metadata_2023-05-24.xlsx
 create mode 100644 assets/metadata/latest/PancDB_RNA-seq_metadata_2023-12-13.xlsx
 rename assets/metadata/latest/{PancDB_Perifusion_metadata_2023-05-24.xlsx => PancDB_UPenn_Perifusion_metadata_2023-05-24.xlsx} (100%)
 create mode 100644 assets/metadata/latest/PancDB_Vanderbilt_Perifusion_metadata_2023-12-22.xlsx
 delete mode 100644 assets/metadata/latest/PancDB_scRNA-seq_metadata_2022-06-15.xlsx
 create mode 100644 assets/metadata/latest/PancDB_scRNA-seq_metadata_2023-12-22.xlsx
```

Any idea why its not working on `hpap`? When you go to the web browser and select `Download All Metadata` here: https://hpap.pmacs.upenn.edu/explore/download?matrix, Do you see any files with `2023-12-22` in the filename?

**Comment by yimsheng** [comment]
@nsamanta here are the files I download from your url;
image
I can see some `2023-12-22`, is that what you are looking for?

**Comment by nsamanta** [comment]
@yimsheng Yes that's what I am looking for. Strangely it is working on a different browser, but not on Chrome

**Comment by yimsheng** [comment]
@nsamanta I am using Chrome by the way. Maybe it has cached the old version. Did you refresh the page?

**Pull request merged**
